# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4a20eb07a7ae0fe9ed49214ae2568d1b215ca782a8660504ae9d2c9682f7fbe2ac98c635f94f43c4b7332de50c5127ea2194aec8b45b5ce5d30bc0c15c7fa83d

test:
  secret_key_base: de9970f95046e0ef681a6824f7c2f45683304eda408c9a1d27e0f971813cc982c1336949ed5f7695ff6df7a511637e400504521526273f04752e5f120d045ef5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
